checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  nodes:
    analysis:
      tests:
       override:
          - command: ./run-my-tests
            coverage:
              file: dice_game/.coverage.xml
        #override:
          #- py-scrutinizer-run
