checks:
  python:
    code_rating: true
    duplicate_code: true

build:
  nodes:
    analysis:
      tests:
        override:
          - command: make coverage
            coverage:
              file: ".coverage"

              format: "py-cc"
