checks:
  python:
    code_rating: true
    duplicate_code: true

build:
  nodes:
    analysis:
      tests:
        override:
          - command: make coverage-xml
            coverage:
              file: ".coverage"
              format: "py-cc"
          - py-scrutinizer-run
