checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  nodes:
    analysis:
      tests:
       override:
          - command: './run-tests.sh'
            coverage:
              file: '.coverage'
              config_file: '.coverage'
        #override:
          #- py-scrutinizer-run
